#pragma once

#include <cstdint>
#include <string_view>

// Diameter AVP code -> name, for turning a wire AVP into an attribute an operator can scope a
// product on by name instead of by number (ADR-0351).
//
// SOURCE: ETSI TS 132 299 V19.0.0 (2025-10) == 3GPP TS 32.299 V19.0.0 Release 19, at
// specs/TS_32-299.pdf -- Table 7.1.0.1 "Use Of IETF Diameter AVPs" (vendor 0) and Table 7.2.0.1
// "3GPP specific AVPs" (vendor 10415), cross-checked against that same document's own per-clause
// prose ("The <Name> AVP (AVP code <N>)").
//
// CITATION CLASS: this is a real 3GPP spec PDF, the same class as the Sy block in dictionary.hpp
// and NOT the freeDiameter C source the base/DCC constants there cite. Disclosed rather than
// silently treated as equivalent.
//
// GENERATED by tools/avp-dictionary/extract_avp_names.py -- do not edit by hand. The generator
// carries the extraction rules, the conflicts it found in the spec text, and the cross-checks that
// must pass before it will emit anything.

namespace diameter_core {

// The AVP's real name, or an empty view when this dictionary does not carry the code. An empty
// result is normal and safe: the caller keeps using the numeric key, which is always emitted.
std::string_view avp_name(std::uint32_t vendor_id, std::uint32_t code) noexcept;

} // namespace diameter_core
