"""Shared helpers for the ADR scripts (stdlib only). Everything an index shows is extracted
mechanically from the ADR text with a regex; a field that is absent stays blank, never written
by hand or synthesised."""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DECISIONS = ROOT / "docs" / "DECISIONS.md"
DIR = ROOT / "docs" / "decisions"
OTHER = DIR / "_other"
ORDER = DIR / "_order.json"
DETAIL = DIR / "INDEX_DETAIL.md"
PREAMBLE = OTHER / "_preamble.md"
INDEX_MARK = "<!-- adr-index: generated by scripts/docs/split_decisions.py; edit via scripts/docs/new_adr.py -->"

HEAD_RE = re.compile(r"^## ", re.M)
ADR_HEAD_RE = re.compile(r"^## ADR-(\d+): (.*)$")


def sha256(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def read(path):
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def write(path, text):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def slugify(title, limit=60):
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    if len(s) > limit:
        s = s[:limit].rsplit("-", 1)[0] or s[:limit]
    return s or "untitled"


def first_sentence(text, cap=160):
    text = re.sub(r"\s+", " ", text).strip()
    m = re.match(r"(.+?[.!?])(\s|$)", text)
    s = m.group(1) if m else text
    return s if len(s) <= cap else s[: cap - 1].rstrip() + "…"


def fields(section):
    """(date, status, decision_sentence, superseded_by) -- all mechanical, blank when absent."""
    date = status = decision = sup = ""
    m = re.search(r"\*\*Date:\*\*\s*([0-9]{4}-[0-9]{2}-[0-9]{2})", section)
    if m:
        date = m.group(1)
    m = re.search(r"\*\*Status:\*\*\s*(.+?)(?=\s\*\*[A-Za-z][^*\n]{0,40}:\*\*|\n|$)", section)
    if m:
        status = first_sentence(m.group(1), 100)
        s = re.search(r"[Ss]uperseded by (ADR-\d+)", m.group(1))
        if s:
            sup = s.group(1)
    m = re.search(r"\*\*Decision:\*\*\s*(.+?)(?:\n\n|$)", section, re.S)
    if m:
        decision = first_sentence(m.group(1), 160)
    return date, status, decision, sup


def cell(s):
    return s.replace("|", "\\|")


def load_order():
    return json.loads(read(ORDER))


def adr_files():
    return sorted(p for p in DIR.glob("ADR-*.md"))


def adr_number(name):
    return int(re.match(r"ADR-(\d+)", name).group(1))


def title_of(path):
    first = read(path).split("\n", 1)[0]
    m = ADR_HEAD_RE.match(first)
    return m.group(2) if m else first[3:]


def render_index(entries, other_entries):
    """entries: [(name, num, title)] in original order. Compact level 1 (what DECISIONS.md carries)."""
    out = [INDEX_MARK, "",
           "One line per ADR; each links to its own file in `docs/decisions/`. Dates, status and the first",
           "sentence of the decision: `docs/decisions/INDEX_DETAIL.md`. Do not edit by hand -- use",
           "`scripts/docs/new_adr.py`; `scripts/docs/check_adr_index.py` fails on drift.", ""]
    for name, num, title in entries:
        out.append(f"- [{num:04d}](decisions/{name}) {title}")
    if other_entries:
        out += ["", "Non-ADR sections (verbatim, in `docs/decisions/_other/`):", ""]
        for name, title in other_entries:
            out.append(f"- [{title}](decisions/_other/{name})")
    return "\n".join(out) + "\n"


def render_detail(rows):
    out = ["# ADR index -- detail", "",
           "Generated; fields are extracted mechanically from each ADR's text (blank = absent in the ADR).",
           "", "| ADR | status | date | title | decision (first sentence) | superseded by | file |",
           "|---|---|---|---|---|---|---|"]
    for name, num, title, date, status, decision, sup in rows:
        out.append(f"| {num:04d} | {cell(status)} | {date} | {cell(title)} | {cell(decision)} | {sup} | [{name}]({name}) |")
    return "\n".join(out) + "\n"
