#!/usr/bin/env bash
# Renders deploy/keycloak/realm-5gc-r19-operators.json.tmpl into deploy/keycloak/import/realm.json
# (gitignored -- Keycloak's --import-realm reads every *.json under that directory at first boot,
# same "generated by a script, never committed" pattern as certs/ -- scripts/gen-lab-pki.sh,
# gui/scripts/gen-operator-pki.sh). ADR-0441.
#
# Secrets are generated once (idempotent -- reruns reuse what is already on disk) and written
# under certs/ so the existing `/certs/` gitignore rule covers them without a new entry:
#   certs/oam-gui-bff/oidc-client-secret        the oam-gui confidential client's secret --
#                                                already created (as a placeholder) by
#                                                gui/scripts/gen-operator-pki.sh; replaced here
#                                                only if it still holds that placeholder.
#   certs/keycloak-lab-users/<user>.password    lab login password (plaintext, lab-only)
#   certs/keycloak-lab-users/<user>.otp-secret  lab TOTP secret (raw bytes ARE the HMAC-SHA1 key
#                                                -- Keycloak does NOT base32-decode this string
#                                                despite generating base32-safe characters for its
#                                                own secrets; verified empirically, ADR-0441).
#                                                deploy/keycloak/totp.py computes the live code.
#
# NOT for production use as-is, same caveats as scripts/gen-lab-pki.sh: plaintext passwords/OTP
# secrets on disk, no secrets manager. Usage: deploy/keycloak/render-realm.sh
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)"
CERTS="${REPO_ROOT}/certs"
LAB_USERS="${CERTS}/keycloak-lab-users"
mkdir -p "${LAB_USERS}" "${SCRIPT_DIR}/import"

rand_secret() { # length
    python3 - "$1" <<'PYEOF'
import secrets, string, sys
n = int(sys.argv[1])
alphabet = string.ascii_letters + string.digits
print("".join(secrets.choice(alphabet) for _ in range(n)))
PYEOF
}

# oam-gui client secret: reuse gen-operator-pki.sh's placeholder file, replacing only the
# placeholder value it ships (never overwrite a value an operator already customised).
mkdir -p "${CERTS}/oam-gui-bff"
secret_file="${CERTS}/oam-gui-bff/oidc-client-secret"
if [ ! -f "${secret_file}" ] || [ "$(cat "${secret_file}")" = "replace-with-the-idp-client-secret" ]; then
    umask 077
    rand_secret 40 > "${secret_file}"
    echo "render-realm: generated ${secret_file}"
fi
OAM_GUI_CLIENT_SECRET="$(cat "${secret_file}")"

seed_user() { # username
    local u="$1"
    umask 077
    [ -f "${LAB_USERS}/${u}.password" ] || rand_secret 24 > "${LAB_USERS}/${u}.password"
    [ -f "${LAB_USERS}/${u}.otp-secret" ] || rand_secret 20 > "${LAB_USERS}/${u}.otp-secret"
}
seed_user shop.agent.lab
seed_user security.admin.lab

SHOP_AGENT_PASSWORD="$(cat "${LAB_USERS}/shop.agent.lab.password")"
SHOP_AGENT_OTP_SECRET="$(cat "${LAB_USERS}/shop.agent.lab.otp-secret")"
SECURITY_ADMIN_PASSWORD="$(cat "${LAB_USERS}/security.admin.lab.password")"
SECURITY_ADMIN_OTP_SECRET="$(cat "${LAB_USERS}/security.admin.lab.otp-secret")"

python3 - "${SCRIPT_DIR}/realm-5gc-r19-operators.json.tmpl" "${SCRIPT_DIR}/import/realm.json" \
    "${OAM_GUI_CLIENT_SECRET}" "${SHOP_AGENT_PASSWORD}" "${SHOP_AGENT_OTP_SECRET}" \
    "${SECURITY_ADMIN_PASSWORD}" "${SECURITY_ADMIN_OTP_SECRET}" <<'PYEOF'
import sys
tmpl_path, out_path, client_secret, shop_pw, shop_otp, sec_pw, sec_otp = sys.argv[1:8]
text = open(tmpl_path).read()
text = (text
        .replace("__OAM_GUI_CLIENT_SECRET__", client_secret)
        .replace("__SHOP_AGENT_PASSWORD__", shop_pw)
        .replace("__SHOP_AGENT_OTP_SECRET__", shop_otp)
        .replace("__SECURITY_ADMIN_PASSWORD__", sec_pw)
        .replace("__SECURITY_ADMIN_OTP_SECRET__", sec_otp))
open(out_path, "w").write(text)
PYEOF

echo "render-realm: wrote ${SCRIPT_DIR}/import/realm.json"
echo "render-realm: lab user secrets under ${LAB_USERS}/ (gitignored, lab-only)"
