apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
