#!/usr/bin/env python3
"""Extract the closure of IPIRIPacketReport from ETSI TS 102 232-3's IPAccessPDU module.

TS33128Payloads (TS 33.128 Annex A) imports exactly one type from ETSI TS 102 232-3:
IPIRIPacketReport. The full IPAccessPDU module imports LI-PS-PDU (TS 102 232-1), which in turn
imports the whole legacy HI2/HI3 module family (UmtsHI2Operations, EpsHI2Operations, VoIP-HI3-IMS,
...) -- none of which TS33128Payloads needs. asn1c resolves imports per module file, so feeding it
the full IPAccessPDU means feeding it that entire family.

This writes an IPAccessPDU module that keeps the module header (same name, same OID) and the
verbatim type definitions in IPIRIPacketReport's closure, and nothing else. Definitions are copied
byte-for-byte from the ETSI source; nothing is rewritten. Re-run when the ETSI schema repository
(specs/etsi/102232-3, BSD-3-Clause, provenance in specs/etsi/SOURCES.md) is updated.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "specs/etsi/102232-3/IPAccessPDU.asn"  # version18(18), the version TS33128Payloads r19 v7 imports; ETSI repo commit 0d26bdf (see specs/etsi/SOURCES.md)
DST = ROOT / "specs/etsi/102232-3/IPAccessPDU-IPIRIPacketReport-subset.asn"
KEYWORDS = {"SEQUENCE", "CHOICE", "OPTIONAL", "OF", "INTEGER", "OCTET", "STRING", "BOOLEAN",
            "ENUMERATED", "SIZE", "UTF8String", "NULL", "DEFAULT", "TRUE", "FALSE", "BIT", "SET",
            "IMPLICIT", "EXPLICIT", "RELATIVE-OID", "OBJECT", "IDENTIFIER", "PrintableString",
            "IA5String", "GeneralizedTime", "UTCTime", "NumericString", "VisibleString", "END"}


def main() -> int:
    src = SRC.read_text()
    header_end = src.index("BEGIN") + len("BEGIN")
    header = src[:header_end]

    def block(name):
        m = re.search(r"^" + re.escape(name) + r" ::=.*?(?=^\S[\w-]* ::=|^END)", src, re.S | re.M)
        return m.group(0) if m else None

    seen, order, todo = set(), [], ["IPIRIPacketReport"]
    while todo:
        t = todo.pop(0)
        if t in seen:
            continue
        b = block(t)
        if b is None:
            print(f"type {t} not found in {SRC}", file=sys.stderr)
            return 1
        seen.add(t)
        order.append(t)
        body = re.sub(r"--.*", "", b).split("::=", 1)[1]
        for ref in re.findall(r"\b([A-Z][A-Za-z0-9-]*)\b", body):
            if ref not in KEYWORDS and ref not in seen:
                todo.append(ref)
    out = header + "\n\n-- Subset generated by tools/li-asn1/trim_ipaccess.py: the closure of\n"
    out += "-- IPIRIPacketReport, verbatim from the ETSI source. See that script for why.\n\n"
    out += "\n".join(block(t).rstrip() + "\n" for t in order) + "\nEND\n"
    DST.write_text(out)
    print(f"{DST.relative_to(ROOT)}: {len(order)} types: {', '.join(order)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
