apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-upf
  labels:
    app.kubernetes.io/name: upf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: upf
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: sbi
      port: {{ .Values.config.port }}
      targetPort: sbi
      protocol: TCP
    - name: pfcp
      port: {{ .Values.config.pfcp_bind_port }}
      targetPort: pfcp
      protocol: UDP
    - name: metrics
      port: 9471
      targetPort: metrics
      protocol: TCP
